# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/karalabe/hid"
    non-go = false
    unused-packages = false

# The current version of logrus, v1.2.0, implements UnmarshalText but not MarshalText.
# As a result, it has a problem marshling Level to JSON.
# Therefore we pin to an older version for now.
[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "c155da19408a8799da419ed3eeb0cb5db0ad5dbc"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.57"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/sohlich/elogrus.v3"

[[constraint]]
  branch = "master"
  name = "github.com/algorand/go-codec"
  source = "github.com/algorand/go-codec.git"

[[constraint]]
  branch = "master"
  name = "github.com/algorand/go-deadlock"
  source = "github.com/algorand/go-deadlock.git"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/algorand/websocket"
  branch = "master"

[[constraint]]
  name = "github.com/gofrs/flock"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/davidlazar/go-crypto"

[[constraint]]
  branch = "master"
  name = "github.com/karalabe/hid"
