name: "PR Benchmark workflow"
on:
  # Push and update benchmarks when a commit is merged into master.
    push:
      branches:
        - ci-master
  # Trigger benchmark test on this PR's commit against master.
    pull_request:
      branches:
        - ci-master
permissions:
  # Push benchmark performance graph to gh-pages branch.
  contents: write
  deployments: write
jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go version
      - name: Build go-algorand
        run: scripts/travis/build.sh
      - name: Run benchmark
        run: go test ./data/transactions/logic -bench 'BenchmarkUintMath' | tee benchmark_output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Push benchmark result
        if: github.event.push
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark_output.txt
          # Where the previous data file is stored
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
      - name: Store benchmark result
        if: github.event.pull_request
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark_output.txt
          # Where the previous data file is stored
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '100%'
          comment-on-alert: true
