name: "codegen verification"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  codegen_verification:
    runs-on: ubuntu-20.04
    services:
      converter:
        image: swaggerapi/swagger-converter@sha256:dcfd1c2537f5f271cb4ec942d08aa59ca41b9a24078040061a772afca7e548ae # v1.0.4
        ports:
          - 8080:8080
    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          path: go-algorand
      - name: Uninstall existing go installation
        run: sudo apt-get -y -q purge golang-go
      - name: Run codegen_verification.sh
        env:
          SWAGGER_CONVERTER_API: "http://localhost:8080"
        run: |
          export GOPATH="${GITHUB_WORKSPACE}/go"
          cd go-algorand
          scripts/travis/codegen_verification.sh
      - name: Slack Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"Codegen verification failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" $SLACK_WEBHOOK
        if: ${{ failure() && (contains(github.ref_name, 'rel/nightly') || contains(github.ref_name, 'rel/beta') || contains(github.ref_name, 'rel/stable') || contains(github.ref_name, 'master')) }}
