name: Label Check
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]
jobs:
  check_label:
    runs-on: ubuntu-latest
    name: Check PR Type label is set
    steps:
      - name: "Failed to find proper PR Type label. Please add one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
        if: |
          !contains(github.event.pull_request.labels.*.name, 'New Feature') &&
          !contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
          !contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
        run: exit 1
      - name: "Found at least one PR Type label. Good job!"
        run: exit 0

