name: Check PR category and type
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]
jobs:
  check_label:
    runs-on: ubuntu-latest
    name: Check PR Category and Type
    steps:
      - name: Checking for correct number of required github pr labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "New Feature, Enhancement, Bug-Fix, Not-Yet-Enabled, Skip-Release-Notes"

      - name: "Checking for PR Category in PR title. Should be like '<category>: <pr title>'."
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "$PR_TITLE" =~ ^.{2,}\:.{2,} ]]; then
            echo "## PR Category is missing from PR title. Please add it like '<category>: <pr title>'." >> GITHUB_STEP_SUMMARY
            exit 1
          fi
